---
- name: '[install] Make sure vim-tiny is uninstalled'
  apt: name=vim-tiny state=absent purge=true
  become: yes
  tags:
    - vim

- name: '[install] Make sure vim-nox is installed'
  apt: name=vim-nox state=present
  become: yes
  tags:
    - vim

- name: '[install] Install CTags'
  apt: name=exuberant-ctags state=present
  tags:
    - vim

#================================ GIT ====================================
# added git as it is a dependency (for small debian distros like minibian)
- name: '[install] Install git'
  apt: name=git state=present
  become: yes
  tags:
    - vim
#=========================================================================

#========================= UPDATE ALTERNATIVES ===========================
# Analog of 'update-alternatives --set editor /usr/bin/vim.nox'
- name: '[install] Setting vim default editor for visudo'
  alternatives:
    name: editor
    path: /usr/bin/vim.nox
  become: yes
  tags:
    - vim
#=========================================================================

#============= SET ENVIRONMENT VARIABLES FOR EDITOR AND TMUX =============
- name: '[install] Setting up environment variable for vim to look good in tmux'
  blockinfile:
    path: /etc/profile.d/env_var.sh
    follow: yes
    create: yes
    mode: 0644
    owner: root
    group: root
    content: |
      export EDITOR="/usr/bin/vim"
      export TERM="xterm-256color"  # For vim colors in tmux
    marker: "# {mark} ======== VIM role: Ansible managed block ========="
  become: yes
  tags:
    - vim
...
