---
#======= CREATE SPECIFIED USERS ======
# The ansible 'user' module seems to use 'useradd' tool on linux
# There is no way to make it use 'adduser' instead and this causes problem

#- name: Create specified users
#  user: name={{ item.username }} password={{ item.passwd }} groups={{ item.groups }} append=yes
#  with_items: "{{ minibian_core_users }}"
#  become: yes
#  tags:
#    - minibian_core

- name: '[create_users] == RED OUTPUT IS OK == Check if users do not already exist'
  command: "id -u {{ item.username }}"
  register: minibian_core_users_stat
  with_items: "{{ minibian_core_users }}"
  ignore_errors: true
  changed_when: false
  tags:
    - minibian_core

- name: '[create_users] Flatten minibian_core_users_stat dictionary'
  set_fact:
    minibian_core_users_exist: "{{ minibian_core_users_exist|default({}) | combine( {item.item.username: item.rc} ) }}"
  with_items: "{{ minibian_core_users_stat.results }}"
  tags:
    - minibian_core

- name: '[create_users] Check if the group exists in the system'
  shell: "getent group | cut -d: -f1"
  register: minibian_core_system_groups
  changed_when: false
  tags:
    - minibian_core

- name: '[create_users] Create specified users using "adduser" only when they (and the groups with same name) do not exist'
  shell: echo "{{ item.passwd }}
    {{ item.passwd }}" | adduser "{{ item.username }}"
  with_items: "{{ minibian_core_users }}"
  become: yes
  when:
    - minibian_core_users_exist.{{ item.username }} != 0
    - item.username not in minibian_core_system_groups.stdout_lines
  tags:
    - minibian_core

- name: '[create_users] Set passwords for users'
  user: name={{ item.username }} password={{ item.passwd }}
  with_items: "{{ minibian_core_users }}"
  become: yes
  tags:
    - minibian_core

- name: '[create_users] Add users to corresponding groups only if these groups exist'
  user: name={{ item[0].username }} groups={{ item[1] }} append=yes
  with_subelements:
    - "{{ minibian_core_users }}"
    - groups
  when: item[1] in minibian_core_system_groups.stdout_lines
  become: yes
  tags:
    - minibian_core

# Fully quoted because of the ': ' on the line. See the Gotchas in the YAML docs.
- name: '[create_users] Modify sudoers file: make sudo group members not being asked for sudo password'
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo\s'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
  become: yes
  when: minibian_core_sudonopasswd is defined and true
  tags:
    - minibian_core
...
