---
#- name: Install zsh dependencies
#  apt: name={{ item }} state=latest
#  with_items:
#    - zsh
#    - git
#  tags:
#    - ohmyzsh
#
#- name: Install powerlevel9k dependencies
#  apt: name={{ item }} state=latest
#  with_items:
#    - bc
#  when: ohmyzsh_powerlevel9k == true
#  tags:
#    - ohmyzsh


- name: Install zsh dependencies
  package: name={{ item }} state=latest
  with_items:
    - zsh
    - git
  tags:
    - ohmyzsh

- name: Install powerlevel9k dependencies
  package: name={{ item }} state=latest
  with_items:
    - bc
  when: ohmyzsh_powerlevel9k == true
  tags:
    - ohmyzsh

...
