---
# Package module does not provide with_items optimisation (same as yum)
# So it is faster to abstract out package managers via facts:
- name: Install zsh dependencies
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=latest"
  with_items:
    - zsh
    - git
  when: ansible_os_family != 'Darwin'
  tags:
    - ohmyzsh

# If installation of just one package needs to be unified:
- name: Install powerlevel9k dependencies
  package: name=bc state=latest
  when: ohmyzsh_powerlevel9k == true
  tags:
    - ohmyzsh

# Upper would work for Darwin too, but I want to specify install_options:
- name: Install zsh dependencies (OSX)
  homebrew:
    install_options:
      - 'with-unicode9'
      - 'without-etcdir'
    name: zsh
    state: latest
  when: ansible_os_family == 'Darwin'
  tags:
    - ohmyzsh
...
