---
- name: Include OSX-Specific variables
  include_vars: osx.yml

- name: Install mpd with Homebrew
  homebrew:
    update_homebrew: yes
    name: mpd
    #state: absent
    state: latest
    install_options: "{{ mpd_osx_install_options }}"

...
