---

- stat: path=/usr/bin/vim.tiny
  register: vim_tiny
  tags:
    - vim

- name: Make sure vim-tiny is uninstalled
  apt: name=vim-tiny state=absent purge=true
  when: vim_tiny.stat.exists == True
  tags:
    - vim

- stat: path=/usr/bin/vim.nox
  register: vim_nox
  tags:
    - vim

- name: Make sure vim-nox is installed
  apt: name=vim-nox state=present
  when: vim_nox.stat.exists == False
  tags:
    - vim

- name: Install CTags
  apt: name=exuberant-ctags state=present
  tags:
    - vim

# added git as it is a dependency (for small debian distros like minibian)
- stat: path=/usr/bin/git
  register: git
  tags:
    - vim

- name: Install git
  apt: name=git state=present
  when: git.stat.exists == False
  tags:
    - vim
...
