---
# tasks file for network

- name: Check '/lib/udev/rules.d/75-persistent-net-generator.rules'
  command: >
    fgrep -q 'KERNEL!="eth*[1-9]|ath*|wlan*[1-9]|msh*|ra*|sta*|ctc*|lcs*|hsi*"' \
      /lib/udev/rules.d/75-persistent-net-generator.rules
  register: result
  ignore_errors: yes
  become: yes

- name: Commenting old pattern in '75-persistent-net-generator.rules' RED OUTPUT IS OK!
  replace:
    path: /lib/udev/rules.d/75-persistent-net-generator.rules
    regexp: '^(KERNEL!=".*$)'
    replace: '#\1'
  when: result|failed     # first method to set condition
  become: yes

- name: Inserting right pattern into '75-persistent-net-generator.rules'
  lineinfile:
    path: /lib/udev/rules.d/75-persistent-net-generator.rules
    insertafter: '^#KERNEL!=".*$'
    line: 'KERNEL!="eth*[1-9]|ath*|wlan*[1-9]|msh*|ra*|sta*|ctc*|lcs*|hsi*"'
    when: result.rc != 0    # second method to set condition
  become: yes

- name: Copying '/etc/network/interfaces'
  copy:
    src: interfaces
    dest: /etc/network/interfaces
  become: yes
  notify: Restart networking service

...
