---
# added git as it is a dependency (for small debian distros like minibian)
- name: '[dependencies] Install git and CTags'
  apt:
    name:
      - git
      - exuberant-ctags
    state: present
  become: yes
  tags:
    - vim
    - vim_dependencies
...
