---
galaxy_info:
  author: Andrew Shagayev
  description: This role installs vim package for terminal usage
  license: BSD
  min_ansible_version: 1.9
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  - name: Debian
    versions:
    - jessie
    - wheezy
  categories:
    - development
    - system
  galaxy_tags:
    - vim
    - Debian
    - Ubuntu
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies: []
...
