---
# tasks file for expandfs

- name: Temporarily set DNS resolver to 8.8.8.8 in order to resolve '*.raspbian.org'
  shell: >
    echo 'nameserver 8.8.8.8' > /etc/resolv.conf
  become: yes

- name: Installing raspi-config if not present
  apt:
    update_cache: yes
    name: raspi-config
    state: present
    force: yes
  become: yes

- name: Expanding filesystem
  command: >
    raspi-config nonint do_expand_rootfs
  become: yes

- name: Running 'partprobe'
  command: >
    partprobe
  become: yes

- name: Running 'resize2fs /dev/mmcblk0p2'
  command: >
    resize2fs /dev/mmcblk0p2
  become: yes
  notify: Filesystem is expanded

...
