---
- name: '[create_users] == RED OUTPUT IS OK == Check if dns is already set to 8.8.8.8'
  command: >
    fgrep -q 'nameserver 8.8.8.8' /etc/resolv.conf
  register: minibian_core_dns
  ignore_errors: yes
  changed_when: false
  tags:
    - expandfs

- name: '[main] Temporarily set dns to 8.8.8.8 in order to resolve *.raspberrypi.org'
  shell: echo 'nameserver 8.8.8.8' > /etc/resolv.conf
  become: yes
  when: minibian_core_dns|failed
  tags:
    - expandfs

- name: '[main] Install parted'
  apt: update_cache=yes name=parted state=present force=yes
  become: yes
  tags:
    - expandfs

- name: '[main] Check unpartitioned space'
  shell: /sbin/parted /dev/mmcblk0 unit gb print free | grep 'Free Space' | tail -n1 | awk '{print $3}'
  register: expandfs_unpartitioned
  changed_when: false
  failed_when: expandfs_unpartitioned.stderr != ""
  become: yes
  tags:
    - expandfs

- name: '[main] Installing raspi-config if not present'
  apt: update_cache=yes name=raspi-config state=present force=yes
  become: yes
  when: expandfs_unpartitioned.stdout != "0.00GB"
  tags:
    - expandfs

- name: '[main] Expanding filesystem'
  command: raspi-config nonint do_expand_rootfs
  become: yes
  when: expandfs_unpartitioned.stdout != "0.00GB"
  tags:
    - expandfs

- name: '[main] Running partprobe'
  command: partprobe
  become: yes
  when: expandfs_unpartitioned.stdout != "0.00GB"
  tags:
    - expandfs

- name: '[main] Running resize2fs /dev/mmcblk0p2'
  command: resize2fs /dev/mmcblk0p2
  become: yes
  when: expandfs_unpartitioned.stdout != "0.00GB"
  notify: Filesystem is expanded
  tags:
    - expandfs
...
