---
- name: '[main] Include Dependencies installation tasks'
  include_tasks: dependencies.yml
  tags:
    - expandfs
    - expandfs_dependencies

- name: '[main] Temporarily set dns to 8.8.8.8 in order to resolve *.raspberrypi.org'
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    mode: 0644
    owner: root
    group: root
  become: yes
  tags:
    - expandfs

- name: '[main] Check unpartitioned space'
  shell: /sbin/parted /dev/mmcblk0 unit gb print free | grep 'Free Space' | tail -n1 | awk '{print $3}'
  register: expandfs_unpartitioned
  changed_when: false
  failed_when: expandfs_unpartitioned.stderr != ""
  become: yes
  tags:
    - expandfs

- name: '[main] Expanding filesystem'
  command: raspi-config nonint do_expand_rootfs
  become: yes
  when: expandfs_unpartitioned.stdout != "0.00GB"
  tags:
    - expandfs

- name: '[main] Running partprobe'
  command: partprobe
  become: yes
  when: expandfs_unpartitioned.stdout != "0.00GB"
  tags:
    - expandfs

- name: '[main] Running resize2fs /dev/mmcblk0p2'
  command: resize2fs /dev/mmcblk0p2
  become: yes
  when: expandfs_unpartitioned.stdout != "0.00GB"
  notify: Filesystem is expanded
  tags:
    - expandfs
...
