---
galaxy_info:
  author: Andrew Shagayev
  description: This role installs zsh and oh-my-zsh
  license: BSD
  min_ansible_version: 1.7

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all

  categories:
    - system

dependencies: []
...
