---
- hosts: rpi
  vars:
    #sshd_users:

  tasks:
    - name: Make test dir ~/test
      file: path=~/test state=directory
      notify: Untagged handler
      tags:
        - test

    - name: Untagged task
      debug:
        msg: task without tag

  handlers:
    - name: Untagged handler
      debug:
        msg: Handler without tag
