---

- name: '[user] Install default configuration'
  template: src=vimrc.j2 dest="{{ vim_root_config }}" owner="{{ item }}" group="{{ item }}" mode=0644
  with_items: "{{ vim_users }}"
  #when: ("{{ vim_users }}" is defined and item != "root")
  when: ("{{ vim_users }}" is defined)
  become: yes    # Required for become_user to work
  become_method: su    # by default it tries to use 'sudo' instead
  become_user: "{{ item }}"
  tags:
    - vim

- name: '[user] Install default plugins'
  template: src=vimrc.bundles.j2 dest="{{ vim_root_bundles }}" owner="{{ item }}" group="{{ item }}" mode=0644
  with_items: "{{ vim_users }}"
  when: ("{{ vim_users }}" is defined)
  become: yes
  become_method: su
  become_user: "{{ item }}"
  tags:
    - vim

- name: '[system] Creating empty /etc/vim/vimrc.emoji if does not exist'
  copy:
    content: ""
    dest: "{{ vim_root_emoji }}"
    force: no
    owner: root
    group: root
    mode: 0644
  become: yes
  when: '"junegunn/vim-emoji" in vim_github_plugins'
  tags:
    - vim

- name: '[user] Install Vundle'
  git:
    repo: https://github.com/gmarik/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
    version: "{{ vim_vundle_version }}"
  with_items: "{{ vim_users }}"
  when: ("{{ vim_users }}" is defined)
  become: yes
  become_method: su
  become_user: "{{ item }}"
  tags:
    - vim

- name: '[user] Copying .vim folder'
  copy:
    src: vim/
    dest: ~/.vim/
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items: "{{ vim_users }}"
  when: ("{{ vim_users }}" is defined)
  become: yes
  become_method: su
  become_user: "{{ item }}"
  tags:
    - vim
# IF this task just hangs, when using:
#   command: "vim +PluginInstall +qal"
#
# this may be because of two things:
#   EITHER .vimrc or .vim files permissions (see 'which sudo' and become_method: su )
#   OR errors in .vimrc
#
# Instead of command: "vim +PluginInstall +qall" we can use:
#
# shell:
#   vim -E -s -c "source ~/.vimrc" -c PluginInstall -c qa
# ignore_errors: yes
#
# For troubleshooting add -V switch to this command and run it directly on the target
#
- name: '[user] Download plugins'
  command: "vim +PluginInstall +qal"
  with_items: "{{ vim_users }}"
  when: ("{{ vim_users }}" is defined)
  become: yes
  become_method: su
  become_user: "{{ item }}"
  tags:
    - vim

- name: '[system] Configure EMOJI for vim'
  template: src=vimrc.emoji.j2 dest="{{ vim_root_emoji }}" owner=root group=root mode=0644
  become: yes
  when: '"junegunn/vim-emoji" in vim_github_plugins' # no need to use "{{ }}" in "when" conditions (Jinja2 feature)

...
