---
# tasks file for ansible-minibian_core

- name: '[main] Setting hostname'
  hostname: name={{ minibian_core_host_name }}
  become: yes
  tags:
    - minibian_core

- name: '[main] Setting timezone'
  timezone: name=America/Vancouver
  become: yes
  tags:
    - minibian_core

- name: '[main] Install sudo'
  apt: name=sudo state=present
#  when: sudo.stat.exists == False
  become: yes
  tags:
    - minibian_core

- name: '[main] Setting EDITOR and TERM environment variables'
  blockinfile:
    path: /etc/profile.d/env_var.sh
    follow: yes
    create: yes
    mode: 0644
    owner: root
    group: root
    content: |
      export EDITOR="/usr/bin/vim"
      export TERM="xterm-256color"  # For vim colors in tmux
    marker: "# {mark} ======== VIM role: Ansible managed block ========="
  become: yes
  tags:
    - minibian_core

#========= CONFIGURING PROMPT ========
# required because 'command: mv ...' will return error
# if /etc/skel does not exist
- name: '[main] check if /etc/skel exists'
  stat: path=/etc/skel
  register: skel_stat
  tags:
    - minibian_core

- name: '[main] check if /etc/skel.dist exists (in case /etc/skel was already backed up)'
  stat: path=/etc/skel.dist
  register: skel_dist_stat
  tags:
    - minibian_core

- name: '[main] Backup distro /etc/skel'
  command: mv /etc/skel /etc/skel.dist
  become: yes
  when: skel_stat.stat.exists == True and skel_dist_stat.stat.exists == False
  tags:
    - minibian_core

- name: '[main] Copying /etc/skel contents'
  copy: src=etc/skel/ dest=/etc/skel
  become: yes
  tags:
    - minibian_core

- name: '[main] Copying .bashrc and .profile to home directory of current user'
  copy: src=etc/skel/ dest="{{ ansible_env.HOME}}/"
  tags:
    - minibian_core
#=====================================

#========== DISTRO UPGRADE ===========
- name: '[main] Upgrading distro'
  apt: upgrade=dist autoclean=yes autoremove=yes
  become: yes
  tags:
    - minibian_core
#====================================

#========= UPDATING FIRMWARE: ========
# needs: echo 'nameserver 8.8.8.8' > /etc/resolv.conf
# which is done in 'expandfs' role.
- name: '[main] Installing latest rpi-update'
  apt: name=rpi-update state=latest force=yes
  become: yes
  tags:
    - minibian_core

- name: '[main] Updating firmware'
  command: rpi-update
  become: yes
  # make use of non-idempotant task:
  # run handler which must be run anyway in the end of playbook (not in the end of current role)
  notify: Change root password
  tags:
    - minibian_core
#=====================================

#======= CREATE SPECIFIED USERS ======
# The ansible 'user' module seems to use 'useradd' tool on linux
# There is no way to make it use 'adduser' instead and this causes problem
- include_tasks: create_users.yml
  tags:
    - minibian_core
#=====================================
...
