---
- hosts: raspberrypi_3
  vars_files:
    - vars.yml

  tasks:

    - name: Make sure /usr/local/share/fonts exists
      file: dest=/usr/local/share/fonts
      become: yes

    - name: Make sure unzip and fontconfig are installed
      apt:
        name: ['unzip', 'fontconfig']
        state: present
      become: yes

    - name: Download Powerline-patched Terminus-ttf font
      unarchive:
        src: http://files.ax86.net/terminus-ttf/files/latest.zip
        dest: /usr/local/share/fonts/
        remote_src: yes
      become: yes

    - name: Install fonts
      command: fc-cache /usr/local/share/fonts
      become: yes

...
