---
- hosts: raspberrypi_3
#- hosts: localhost

#  vars_files:
#    - vars.yml
#  vars:

  roles:
#    - ansible-network
#    - ansible-expandfs
#    - ansible-vim
#    - ansible-ohmyzsh
#    - ansible-terminus_powerline
#    - ansible-nerdfonts
    - ansible-mpd
...
