---
- hosts: raspberrypi_3
#- hosts: localhost
#  vars_files:
#    - vars.yml
#  vars:

  roles:
#    - network
#    - expandfs
#    - vim
#    - powerline-fonts
#    - ohmyzsh
    - mpd
#    - ansible-terminus-powerline
...
