---
#========================== INSTALL RELATED ============================
mpd_firewall_zones: [ 'public' ]
#=======================================================================

#=========================== CONFIG RELATED ============================
# music directory can also be nfs share if mpd built --with-libnfs
#   mpd_music_dir: nfs://192.168.1.1/music
mpd_music_dir: /var/lib/mpd/music
mpd_playlist_dir: /var/lib/mpd/playlists

mpd_db_file: /var/lib/mpd/mpd.db
mpd_sticker_file: /var/lib/mpd/sticker.db
mpd_log_file: syslog
mpd_state_file: /var/lib/mpd/mpdstate

mpd_user: mpd

mpd_outputs:
  - name: "Null Output"
    type: "null"

  - name: "My ALSA Device"
    type: "alsa"
    device: "hw:0,0"            # optional
    format: "44100:16:2"        # optional
    mixer_device: "default"     # optional
    mixer_control: "PCM"        # optional
    mixer_index: "0"            # optional

#  - name: "MPD PulseAudio Output"
#    type: "pulse"
#    server: "remote_server"     # optional
#    sink: "remote_server_sink"  # optional
#=======================================================================
...
